<a href="https://colab.research.google.com/github/akhilakalikiri/Shala_learning/blob/main/module1_DataScience/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing libraries

import numpy as np
import pandas as pd

In [ ]:
# numpy array declaration

arr1=np.array([1,2,3])
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
#type

print(type(arr1))

#dtype

print(arr1.dtype)

#astype

arr11=arr1.astype('f')
print(arr11)
print(type(arr11))
print(arr11.dtype)


<class 'numpy.ndarray'>
int32
[1. 2. 3.]
<class 'numpy.ndarray'>
float32


In [ ]:
#dimension

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

#changing dimension

arr12=np.array([1,2,3],ndmin=2)
print(arr12.ndim)

1
2
3
2


In [ ]:
#array copy and view

arrcopy=arr1.copy()
arrview=arr1.view()
print(arrcopy)
print(arrview)
arr1[0]=5
print(arrcopy)
print(arrview)

[1 2 3]
[1 2 3]
[1 2 3]
[5 2 3]


In [ ]:
#owning the data
#returns none if array owns the data

print(arrcopy.base)
print(arrview.base)

None
[5 2 3]


In [ ]:
#array shapes

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

print(arr1.size)
#reshaping arrays

print(arr2.reshape(3,2))

#changing array into one dimensional array(flattening)

print(arr3.flatten())
print(arr3.reshape(-1))

(3,)
(2, 3)
(2, 2, 2)
3
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [ ]:
#iterating arrays

for i in arr1:
    print(i)


for i in arr2:
    print(i)


for i in arr2:
    for j in i:
        print(j)

#nditer

for i in np.nditer(arr3):
    print(i)

5
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6
1
2
3
4
5
6
7
8


In [ ]:
#denumerate-tells about the positions


for idx,i in np.ndenumerate(arr3):
    print(idx,i)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [ ]:
#stacking
#concatenate

a1=np.array([[1,2],[3,4]])
a2=np.array([[6,7],[8,9]])
print(np.concatenate((a1,a2),axis=0))
print(np.concatenate((a1,a2),axis=1))

#hstack
print(np.hstack((a1,a2)))


#vstack
print(np.vstack((a1,a2)))


#dstack
print(np.dstack((a1,a2)))




[[1 2]
 [3 4]
 [6 7]
 [8 9]]
[[1 2 6 7]
 [3 4 8 9]]
[[1 2 6 7]
 [3 4 8 9]]
[[1 2]
 [3 4]
 [6 7]
 [8 9]]
[[[1 6]
  [2 7]]

 [[3 8]
  [4 9]]]


In [ ]:
#spliting arrays

print(np.array_split(arr1,4))
print(np.array_split(arr2,2))
print(np.array_split(arr3,2))

[array([5]), array([2]), array([3]), array([], dtype=int32)]
[array([[1, 2, 3]]), array([[4, 5, 6]])]
[array([[[1, 2],
        [3, 4]]]), array([[[5, 6],
        [7, 8]]])]


In [ ]:
#searching arrays

print(np.where(arr1==5))
print(np.searchsorted(arr1,7))
print(np.searchsorted(arr1,7,side="Left"))

(array([0], dtype=int64),)
3
3


In [ ]:
#sorting array

print(np.sort(arr1))
print(np.sort(arr2,axis=0))
print(np.sort(arr2,axis=1))

arr22=[[1,5,2],[2,1,5]]
print(np.sort(arr22))

[2 3 5]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 5]
 [1 2 5]]


In [ ]:
#printing range of numbers___staring,ending,step

range1=np.arange(1,20,2)
print(range1)

[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
#dividing the number

range2=np.linspace(1,10,30)
print(range2)

[ 1.          1.31034483  1.62068966  1.93103448  2.24137931  2.55172414
  2.86206897  3.17241379  3.48275862  3.79310345  4.10344828  4.4137931
  4.72413793  5.03448276  5.34482759  5.65517241  5.96551724  6.27586207
  6.5862069   6.89655172  7.20689655  7.51724138  7.82758621  8.13793103
  8.44827586  8.75862069  9.06896552  9.37931034  9.68965517 10.        ]


In [ ]:
#random numbers genearation

rand=np.random.rand(10)
print(rand)
ran=np.random.randint(10,20,4)
print(ran)
rand1=np.random.rand(1,2)
print(rand1)

[0.21166922 0.08864658 0.04157089 0.17798535 0.73667364 0.79951653
 0.54702816 0.55557637 0.60519459 0.39583557]
[17 18 13 10]
[[0.3220733  0.60827375]]


In [ ]:
#printing zeros and ones

print(np.zeros(10))
print(np.zeros((2,3)))

print(np.ones(10))
print(np.ones((10,10,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  

In [ ]:
#repeating arrays

print(np.repeat(arr1,3))
print(np.tile(arr1,3))

[5 5 5 2 2 2 3 3 3]
[5 2 3 5 2 3 5 2 3]


In [ ]:
#identity array

print(np.eye(3))
print(np.eye(5))
print(np.eye(4))

print(np.diag([1,2,3]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
#printing daigonal elements

ray=np.random.rand(5,5)
print(ray,'\n')

print(np.diag(ray))

[[0.93923559 0.06288331 0.99013429 0.0864703  0.5425907 ]
 [0.37553564 0.38217833 0.35866056 0.26467807 0.87465779]
 [0.78159347 0.9810109  0.01322772 0.21815467 0.43312386]
 [0.92281783 0.26156641 0.82303588 0.06600678 0.71618838]
 [0.55105873 0.69353028 0.84540424 0.6499385  0.15768995]] 

[0.93923559 0.38217833 0.01322772 0.06600678 0.15768995]


In [ ]:
#opearations on numbers

print(arr1+10)
print(arr1/2)
print(np.exp(arr1))
print(np.log2(arr1))
print(np.sin(arr1))
print(np.max(arr1))

[15 12 13]
[2.5 1.  1.5]
[148.4131591    7.3890561   20.08553692]
[2.32192809 1.         1.5849625 ]
[-0.95892427  0.90929743  0.14112001]
5


In [ ]:
#sum of the values in a array and min

print(np.sum(arr1))

#sum of values in rows
print(np.sum(arr2,axis=1))#rows
print(np.sum(arr2,axis=0))#columns

print(np.max(arr2,axis=0))
print(np.max(arr2,axis=1))

10
[ 6 15]
[5 7 9]
[4 5 6]
[3 6]


In [ ]:
#some data analytics functions


print(np.mean(arr1))
print(np.mean(arr2,axis=0))
print(np.mean(arr2,axis=1))

print(np.median(arr1))
print(np.median(arr3,axis=0))
print(np.median(arr3,axis=1))

#stranderd deviation

print(np.std(arr1))
print(np.var(arr1))

3.3333333333333335
[2.5 3.5 4.5]
[2. 5.]
3.0
[[3. 4.]
 [5. 6.]]
[[2. 3.]
 [6. 7.]]
1.247219128924647
1.5555555555555556


In [ ]:
x=np.diag([1,2,3])

#transpose

print(x)
print(x.T)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
print(arr2)
print(arr2[1,1:])

[[1 2 3]
 [4 5 6]]
[5 6]


In [ ]:
#appending arrays

print(arr1)
arrc=np.append(arr1,4)
print(arrc)
arra=np.insert(arr1,0,[1,2,3])
print(arra)
arrd=np.delete(arr1,0)
print(arrd)
arre=np.delete(arr1,[0,1])
print(arre)

[5 2 3]
[5 2 3 4]
[1 2 3 5 2 3]
[2 3]
[3]


In [ ]:
#printing unique values

arr1=[1,3,1,3,2,2,34,5,5]
print(np.unique(arr1))
unique,count=np.unique(arr1,return_counts=True)
print(unique)
print(count)


[ 1  2  3  5 34]
[ 1  2  3  5 34]
[2 2 2 2 1]


In [ ]:
#interssection.differnation

arr1=np.array([1,3,2,1,24,6])
arr2=np.array([5,3,2,1,4,24,3,9])
print(np.intersect1d(arr1,arr2))
print(np.union1d(arr1,arr2))
print(np.setdiff1d(arr1,arr2))
print(np.setxor1d(arr1,arr2))

[ 1  2  3 24]
[ 1  2  3  4  5  6  9 24]
[6]
[4 5 6 9]


In [ ]:
import numpy as np

# Create two arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
C = np.matmul(A, B)
print("Matrix Multiplication:")
print(C)
print()

# Matrix transpose
D = np.transpose(A)
print("Matrix Transpose:")
print(D)
print()

# Matrix determinant
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
print("Determinant of A:", det_A)
print("Determinant of B:", det_B)
print()

# Matrix inverse
A_inv = np.linalg.inv(A)
B_inv = np.linalg.inv(B)
print("Inverse of A:")
print(A_inv)
print("Inverse of B:")
print(B_inv)
print()

# Eigenvalues and eigenvectors
eigenvalues_A, eigenvectors_A = np.linalg.eig(A)
eigenvalues_B, eigenvectors_B = np.linalg.eig(B)
print("Eigenvalues of A:")
print(eigenvalues_A)
print("Eigenvectors of A:")
print(eigenvectors_A)
print("Eigenvalues of B:")
print(eigenvalues_B)
print("Eigenvectors of B:")
print(eigenvectors_B)
